# Generated by Django 5.0.1 on 2024-02-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutty", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketitem",
            name="number_of_boxes",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="basketitem",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
