# Generated by Django 5.0.1 on 2024-02-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nutty", "0002_basketitem_number_of_boxes_alter_basketitem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basketitem",
            name="number_of_boxes",
        ),
    ]
