# Generated by Django 5.0.1 on 2024-02-24 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutty", "0003_remove_basketitem_number_of_boxes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="basket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="nutty.basket"
            ),
        ),
    ]
