# Generated by Django 4.2.10 on 2024-02-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutty', '0003_alter_order_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu_item',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
